# Generated by Django 3.0.3 on 2020-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='random',
            field=models.IntegerField(default=0),
        ),
    ]
