# Generated by Django 3.0.3 on 2020-05-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_choice_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='random',
        ),
    ]
