# Generated by Django 3.0.3 on 2020-05-08 23:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_auto_20200508_2316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('choice', 'usuario')},
        ),
    ]
