# Generated by Django 3.0.3 on 2020-05-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20200509_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='uploads/none/no-img.jpeg', upload_to='uploads/'),
        ),
    ]
