# Generated by Django 3.0.3 on 2020-05-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
