# Generated by Django 3.0.3 on 2020-05-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_comentario_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Question'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='respuesta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='boards.Comentario'),
        ),
    ]
